### ISSUE TITLE
ops.json should be permissions.json

### ISSUE THREAD

**Issue by paulmiu** [BoxOfSnoo/docker-bedrockserver#1]
Thanks a lot for your effort! This repository was exactly what I was looking for.

You're having an `ops.json` file in the `data` directory to make players operators. But in the `bedrock_server_how_to.html` (included in the official bedrock server zip) they're stating to use the `permissions.json` for that purpose.

Here is the **Permissions** part from their docs:

> You can adjust player specific permissions by assigning them roles in the `permissions.json` that is placed in the same directory as the server executable. The file contains a simple JSON object with XUIDs and permissions. Valid permissions are: `operator`, `member`, `visitor`. Every player that connects with these accounts will be treated according to the set premission. If you change this file while the server is running, then run the command `permissions reload` to make sure that the server knows about your new change. You could also list the current permissions with `permissions list`. Note that `online-mode` needs to be enabled for this feature to work since xuid requires online verification of the user account. If a new player that is not in this list connects, the `default-player-permission-level` option will apply.
> 
> Example `permissions.json` file:
> 
>     [
>         {
>             "permission": "operator",
>             "xuid": "451298348"
>         },
>         {
>             "permission": "member",
>             "xuid": "52819329"
>         },
>         {
>             "permission": "visitor",
>             "xuid": "234114123"
>         }
>     ]

So the `ops.json` should be called `permissions.json`. After renaming the file and adjusting the specific mount volume in the `docker-compose.yml` it works fine for me.

IMHO it would also be very helpful to have the `bedrock_server_how_to.html` within the repository or even better have it integrated in the `README.md`.

**Comment by BoxOfSnoo** [comment]
Thanks for your comments!

I will change the name of the ops.json.  I only include it in the data folder so that if you make adjustments to it manually, it won't get overwritten when you restart the container.

I don't think I will include the howto .html, since I download the package each time - the howto may (likely) be different with different server downloads anyway.  Maybe I will include a recommendation to read it from the download package.
